comment out gitflow run (#152)
Co-authored-by: Tina Gohil <tinagohil@Tinas-MacBook-Pro.local>

diff --git a/.github/workflows/test-adminUi-regression.yml b/.github/workflows/test-adminUi-regression.yml
--- a/.github/workflows/test-adminUi-regression.yml
+++ b/.github/workflows/test-adminUi-regression.yml
@@ -1,81 +1,81 @@
-name: "| Test env | Manage family support services and accounts - Regression Pack |"
-
-on:
-  schedule:
-    - cron: "30 06 * * *"
-  workflow_dispatch:
-
-
-jobs:
-  cypress-run:
-    environment: information sharing - admin-ui
-    env:
-      CYPRESS_BASE_URL: "https://test.manage-family-support-services-and-accounts.education.gov.uk/"
-    name: " 🛎️ RegressionTests - IS - Admin UI - Test Environment "
-    runs-on: ubuntu-22.04
-    strategy:
-      fail-fast: false
-    steps:
-      - run: date
-      - uses: actions/checkout@v2
-      - uses: cypress-io/github-action@v4
-        name: cypress
-        id: cypress
-        continue-on-error: true
-        with:
-          quiet: true
-          browser: chrome
-          headless: true
-          spec: "cypress/e2e/**/*.spec.js"
-        env:
-          DEBUG: '@cypress/github-action'   
-          CYPRESS_oneloginusername: ${{ secrets.ONELOGIN_ID }}
-          CYPRESS_oneloginpassword: ${{ secrets.ONELOGIN_PASSWORD }}
-          CYPRESS_lamanoneloginusername: ${{ secrets.LAMAN_ONELOGIN_ID }}
-          CYPRESS_lamanoneloginpassword: ${{ secrets.LAMAN_ONELOGIN_PASSWORD }}
-          CYPRESS_vcsmanoneloginusername: ${{ secrets.VCSMAN_ONELOGIN_ID }}
-          CYPRESS_vcsmanoneloginpassword: ${{ secrets.VCSMAN_ONELOGIN_PASSWORD }}
-          CYPRESS_username: ${{ secrets.INTEGRATION_ID }}
-          CYPRESS_password: ${{ secrets.INTEGRATION_PASSWORD }}
-      - uses: actions/upload-artifact@v2
-        with:
-          name: report
-          path: ./cypress/reports/
-
-      - name: Checkout reports repo
-        uses: actions/checkout@v2
-        with:
-          ref: reports
-          path: reports_repo
-
-      - name: Copy report into reports repo
-        run: |
-          cd reports_repo
-          DATE=$(date +%d-%m-%Y)
-          [ -e docs/adminui/$DATE ] && rm -rf docs/adminui/$DATE
-          cp -a ../cypress/reports/html  docs/adminui/$DATE
-          pushd docs/adminui/$DATE
-          rm -rf assets
-          rm -rf screenshots
-          rm -rf videos
-          ln -s ../../assets/
-          popd
-          git add docs .
-      - name: Commit todays report to reports branch
-        run: |
-          cd reports_repo
-          git config --local user.email "DFE-Digital+github-actions[bot]@users.noreply.github.com"
-          git config --local user.name "github-actions[bot]"
-          git commit -m "report for $(date +%d-%m-%Y)" -a
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: reports
-          directory: reports_repo
-      - name: Set build status based on Cypress outcome
-        if: steps.cypress.outcome != 'success'
-        run: exit 1
-        
-
-     
+#name: "| Test env | Manage family support services and accounts - Regression Pack |"
+#
+#on:
+#  schedule:
+#    - cron: "30 06 * * *"
+#  workflow_dispatch:
+#
+#
+#jobs:
+#  cypress-run:
+#    environment: information sharing - admin-ui
+#    env:
+#      CYPRESS_BASE_URL: "https://test.manage-family-support-services-and-accounts.education.gov.uk/"
+#    name: " 🛎️ RegressionTests - IS - Admin UI - Test Environment "
+#    runs-on: ubuntu-22.04
+#    strategy:
+#      fail-fast: false
+#    steps:
+#      - run: date
+#      - uses: actions/checkout@v2
+#      - uses: cypress-io/github-action@v4
+#        name: cypress
+#        id: cypress
+#        continue-on-error: true
+#        with:
+#          quiet: true
+#          browser: chrome
+#          headless: true
+#          spec: "cypress/e2e/**/*.spec.js"
+#        env:
+#          DEBUG: '@cypress/github-action'   
+#          CYPRESS_oneloginusername: ${{ secrets.ONELOGIN_ID }}
+#          CYPRESS_oneloginpassword: ${{ secrets.ONELOGIN_PASSWORD }}
+#          CYPRESS_lamanoneloginusername: ${{ secrets.LAMAN_ONELOGIN_ID }}
+#          CYPRESS_lamanoneloginpassword: ${{ secrets.LAMAN_ONELOGIN_PASSWORD }}
+#          CYPRESS_vcsmanoneloginusername: ${{ secrets.VCSMAN_ONELOGIN_ID }}
+#          CYPRESS_vcsmanoneloginpassword: ${{ secrets.VCSMAN_ONELOGIN_PASSWORD }}
+#          CYPRESS_username: ${{ secrets.INTEGRATION_ID }}
+#          CYPRESS_password: ${{ secrets.INTEGRATION_PASSWORD }}
+#      - uses: actions/upload-artifact@v2
+#        with:
+#          name: report
+#          path: ./cypress/reports/
+#
+#      - name: Checkout reports repo
+#        uses: actions/checkout@v2
+#        with:
+#          ref: reports
+#          path: reports_repo
+#
+#      - name: Copy report into reports repo
+#        run: |
+#          cd reports_repo
+#          DATE=$(date +%d-%m-%Y)
+#          [ -e docs/adminui/$DATE ] && rm -rf docs/adminui/$DATE
+#          cp -a ../cypress/reports/html  docs/adminui/$DATE
+#          pushd docs/adminui/$DATE
+#          rm -rf assets
+#          rm -rf screenshots
+#          rm -rf videos
+#          ln -s ../../assets/
+#          popd
+#          git add docs .
+#      - name: Commit todays report to reports branch
+#        run: |
+#          cd reports_repo
+#          git config --local user.email "DFE-Digital+github-actions[bot]@users.noreply.github.com"
+#          git config --local user.name "github-actions[bot]"
+#          git commit -m "report for $(date +%d-%m-%Y)" -a
+#      - name: Push changes
+#        uses: ad-m/github-push-action@master
+#        with:
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          branch: reports
+#          directory: reports_repo
+#      - name: Set build status based on Cypress outcome
+#        if: steps.cypress.outcome != 'success'
+#        run: exit 1
+#        
+#
+#     
